export const demoEquipo = [
  { id: '00000000-0000-0000-0000-000000000001', nombre: 'Pablo', activo: true },
  { id: '00000000-0000-0000-0000-000000000002', nombre: 'Diego', activo: true },
  { id: '00000000-0000-0000-0000-000000000003', nombre: 'Mónica', activo: true },
  { id: '00000000-0000-0000-0000-000000000004', nombre: 'Ángel', activo: true },
  { id: '00000000-0000-0000-0000-000000000005', nombre: 'Priscila', activo: true },
];

export const demoClientes = [
  {
    id: 'demo-cliente-1',
    nombre: 'Martín Alvarez',
    email: 'martin@example.com',
    celular: '+54 9 11 5555-1234',
    fecha_nacimiento: '1988-05-22',
    direccion: 'Av. Callao 1234',
    localidad: 'Recoleta',
    ocupacion: 'Abogado',
    como_llego: 'referido',
    talle_habitual: '50',
    preferencias: 'Azul marino, lana fría, calce entallado.',
    notas: 'Cliente frecuente para trajes laborales.',
    created_at: new Date().toISOString(),
    created_by: demoEquipo[0].id,
    compras: [{ id: 'demo-compra-1', estado: 'listo' }],
    interacciones: [{ fecha: new Date().toISOString() }],
  },
  {
    id: 'demo-cliente-2',
    nombre: 'Federico Braun',
    email: 'federico@example.com',
    celular: '+54 9 11 5555-7788',
    fecha_nacimiento: '1992-08-14',
    direccion: 'Juncal 890',
    localidad: 'Palermo',
    ocupacion: 'Arquitecto',
    como_llego: 'instagram',
    talle_habitual: '48',
    preferencias: 'Tonos claros, camisas blancas, pantalón sin pinzas.',
    notas: '',
    created_at: '2026-04-12T10:00:00Z',
    created_by: demoEquipo[2].id,
    compras: [{ id: 'demo-compra-2', estado: 'en_proceso' }],
    interacciones: [{ fecha: '2025-09-01T13:00:00Z' }],
  },
];

export const demoCompras = [
  {
    id: 'demo-compra-1',
    cliente_id: 'demo-cliente-1',
    fecha: '2026-05-15',
    tipo: 'a_medida',
    prendas: [{ prenda: 'traje', detalle: 'azul marino, lana fría' }],
    evento: 'casamiento',
    fecha_evento: '2026-05-28',
    precio: 980000,
    estado: 'listo',
    atendido_por: demoEquipo[0].id,
    equipo: { nombre: 'Pablo' },
    clientes: { nombre: 'Martín Alvarez' },
    notas: 'Primera prueba ok.',
  },
  {
    id: 'demo-compra-2',
    cliente_id: 'demo-cliente-2',
    fecha: '2026-05-10',
    tipo: 'ready_to_wear',
    prendas: [{ prenda: 'saco', detalle: 'gris medio' }],
    evento: 'laboral',
    fecha_evento: '2026-05-24',
    precio: 320000,
    estado: 'en_proceso',
    atendido_por: demoEquipo[2].id,
    equipo: { nombre: 'Mónica' },
    clientes: { nombre: 'Federico Braun' },
    notas: '',
  },
];

export const demoMedidas = [
  {
    id: 'demo-medida-1',
    cliente_id: 'demo-cliente-1',
    tipo_prenda: 'traje',
    fecha_toma: '2026-05-15',
    datos: { largo_saco: 74, ancho_hombros: 46, contorno_pecho: 102, largo_manga: 64, cintura_pantalon: 88, entrepierna: 79 },
    notas: 'Hombro izquierdo apenas más bajo.',
    equipo: { nombre: 'Pablo' },
  },
];

export const demoInteracciones = [
  {
    id: 'demo-int-1',
    cliente_id: 'demo-cliente-1',
    fecha: new Date().toISOString(),
    tipo: 'prueba',
    canal: 'presencial',
    equipo: { nombre: 'Pablo' },
    notas: 'Probó saco y pantalón. Ajustar largo de manga.',
  },
  {
    id: 'demo-int-2',
    cliente_id: 'demo-cliente-2',
    fecha: '2025-09-01T13:00:00Z',
    tipo: 'consulta',
    canal: 'whatsapp',
    equipo: { nombre: 'Mónica' },
    notas: 'Consultó por saco para reuniones.',
  },
];
